export const BRANCHES = {
  infection: {
    id: 'infection',
    label: 'Infection',
    color: '#8d0f0a',
    icon: '◇',
    description: 'Enhance shape-shifter abilities, reduced cooldowns, new forms.',
    nodes: [
      { id: 'i1', label: 'Minor Adaptation', type: 'passive', cost: 1,
        description: '+5% damage resistance',
        effects: { damageResistance: 0.05 } },
      { id: 'i2', label: 'Viral Resilience', type: 'passive', cost: 2,
        description: '+10% health regen speed',
        effects: { healthRegenMult: 1.10 } },
      { id: 'i3', label: 'Quick Shift', type: 'passive', cost: 3,
        description: '-10% transformation cooldown',
        effects: { transformCooldownMult: 0.90 } },
      { id: 'i4', label: 'Chitinous Shell', type: 'passive', cost: 4,
        description: '+15% max health',
        effects: { maxHealthMult: 1.15 } },
      { id: 'i5', label: 'Camouflage', type: 'active', cost: 5,
        description: 'Toggle invisibility for 5s',
        effects: { ability: 'camouflage', duration: 5, cooldown: 30 } },
      { id: 'i6', label: 'Enhanced Shift', type: 'passive', cost: 6,
        description: '-20% transformation cooldown',
        effects: { transformCooldownMult: 0.80 } },
      { id: 'i7', label: 'Tendril Whip', type: 'active', cost: 7,
        description: 'Extended melee range attack',
        effects: { ability: 'tendril_whip', range: 5, damage: 80 } },
      { id: 'i8', label: 'Regenerative Mass', type: 'passive', cost: 8,
        description: '+25% health regen',
        effects: { healthRegenMult: 1.25 } },
      { id: 'i9', label: 'Apex Form', type: 'active', cost: 9,
        description: 'Transformation with enhanced abilities for 10s',
        effects: { ability: 'apex_form', duration: 10, cooldown: 60,
                   damageMult: 1.5, speedMult: 1.3 } },
      { id: 'i10', label: 'Perfect Symbiosis', type: 'passive', cost: 10,
        description: 'All Infection bonuses doubled',
        effects: { perfectSymbiosis: true } },
    ],
  },
  combat: {
    id: 'combat',
    label: 'Combat',
    color: '#ff3f31',
    icon: '◆',
    description: 'Melee damage, fire rate, reload speed, health.',
    nodes: [
      { id: 'c1', label: 'Iron Fist', type: 'passive', cost: 1,
        description: '+5% melee damage',
        effects: { meleeDamageMult: 1.05 } },
      { id: 'c2', label: 'Quick Draw', type: 'passive', cost: 2,
        description: '+5% fire rate',
        effects: { fireRateMult: 1.05 } },
      { id: 'c3', label: 'Fast Hands', type: 'passive', cost: 3,
        description: '+5% reload speed',
        effects: { reloadSpeedMult: 1.05 } },
      { id: 'c4', label: 'Toughness', type: 'passive', cost: 4,
        description: '+5% max health',
        effects: { maxHealthMult: 1.05 } },
      { id: 'c5', label: 'Adrenaline Surge', type: 'active', cost: 5,
        description: '+25% damage for 8s on kill',
        effects: { ability: 'adrenaline', duration: 8, damageMult: 1.25 } },
      { id: 'c6', label: 'Deadly Precision', type: 'passive', cost: 6,
        description: '+10% melee damage',
        effects: { meleeDamageMult: 1.10 } },
      { id: 'c7', label: 'Rapid Fire', type: 'passive', cost: 7,
        description: '+10% fire rate',
        effects: { fireRateMult: 1.10 } },
      { id: 'c8', label: 'Combat Reloader', type: 'passive', cost: 8,
        description: '+10% reload speed',
        effects: { reloadSpeedMult: 1.10 } },
      { id: 'c9', label: 'Berserker', type: 'active', cost: 9,
        description: '+50% damage, -20% defense for 6s',
        effects: { ability: 'berserker', duration: 6, damageMult: 1.50, defenseMult: 0.80 } },
      { id: 'c10', label: 'Unstoppable', type: 'passive', cost: 10,
        description: '+15% max health, +15% all damage',
        effects: { maxHealthMult: 1.15, damageMult: 1.15 } },
    ],
  },
  movement: {
    id: 'movement',
    label: 'Movement',
    color: '#79d2ff',
    icon: '△',
    description: 'Sprint speed, jump height, wall-run duration, fall damage reduction.',
    nodes: [
      { id: 'm1', label: 'Light Step', type: 'passive', cost: 1,
        description: '+5% sprint speed',
        effects: { sprintSpeedMult: 1.05 } },
      { id: 'm2', label: 'Spring Legs', type: 'passive', cost: 2,
        description: '+5% jump height',
        effects: { jumpHeightMult: 1.05 } },
      { id: 'm3', label: 'Wall Runner', type: 'passive', cost: 3,
        description: '+20% wall-run duration',
        effects: { wallRunDurationMult: 1.20 } },
      { id: 'm4', label: 'Feather Fall', type: 'passive', cost: 4,
        description: '-10% fall damage',
        effects: { fallDamageMult: 0.90 } },
      { id: 'm5', label: 'Air Dash', type: 'active', cost: 5,
        description: 'Perform an air dash (20m)',
        effects: { ability: 'air_dash', distance: 20, cooldown: 15 } },
      { id: 'm6', label: 'Speed Demon', type: 'passive', cost: 6,
        description: '+10% sprint speed',
        effects: { sprintSpeedMult: 1.10 } },
      { id: 'm7', label: 'High Jumper', type: 'passive', cost: 7,
        description: '+10% jump height',
        effects: { jumpHeightMult: 1.10 } },
      { id: 'm8', label: 'Slide Expert', type: 'passive', cost: 8,
        description: '+30% slide speed',
        effects: { slideSpeedMult: 1.30 } },
      { id: 'm9', label: 'Double Jump', type: 'active', cost: 9,
        description: 'Unlock double jump',
        effects: { ability: 'double_jump' } },
      { id: 'm10', label: 'Phantom Move', type: 'active', cost: 10,
        description: '+50% speed, no fall damage for 5s',
        effects: { ability: 'phantom_move', duration: 5, cooldown: 45,
                   speedMult: 1.50, fallDamageMult: 0 } },
    ],
  },
  stealth: {
    id: 'stealth',
    label: 'Stealth',
    color: '#5a8a6a',
    icon: '○',
    description: 'Noise reduction, detection range, silent takedowns.',
    nodes: [
      { id: 's1', label: 'Quiet Step', type: 'passive', cost: 1,
        description: '-10% noise',
        effects: { noiseMult: 0.90 } },
      { id: 's2', label: 'Shadow', type: 'passive', cost: 2,
        description: '-10% detection range',
        effects: { detectionRangeMult: 0.90 } },
      { id: 's3', label: 'Backstab', type: 'passive', cost: 3,
        description: '+25% melee damage from behind',
        effects: { backstabMeleeMult: 1.25 } },
      { id: 's4', label: 'Silent Killer', type: 'passive', cost: 4,
        description: '-20% noise',
        effects: { noiseMult: 0.80 } },
      { id: 's5', label: 'Silent Takedown', type: 'active', cost: 5,
        description: 'Unlock silent takedowns',
        effects: { ability: 'silent_takedown' } },
      { id: 's6', label: 'Ghost', type: 'passive', cost: 6,
        description: '-20% detection range',
        effects: { detectionRangeMult: 0.80 } },
      { id: 's7', label: 'Ninja', type: 'active', cost: 7,
        description: '5s of silent movement',
        effects: { ability: 'ninja', duration: 5, cooldown: 30, noiseMult: 0 } },
      { id: 's8', label: 'Assassin', type: 'passive', cost: 8,
        description: '+50% melee damage from behind',
        effects: { backstabMeleeMult: 1.50 } },
      { id: 's9', label: 'Shadow Clone', type: 'active', cost: 9,
        description: 'Create a decoy for 8s',
        effects: { ability: 'shadow_clone', duration: 8, cooldown: 45 } },
      { id: 's10', label: 'Perfect Stealth', type: 'active', cost: 10,
        description: '10s invisibility (breaks on movement)',
        effects: { ability: 'perfect_stealth', duration: 10, cooldown: 90 } },
    ],
  },
  survival: {
    id: 'survival',
    label: 'Survival',
    color: '#a8e86a',
    icon: '▢',
    description: 'Health regen, inventory size, damage resistance.',
    nodes: [
      { id: 'v1', label: 'Bandage', type: 'passive', cost: 1,
        description: '+5% health regen rate',
        effects: { healthRegenMult: 1.05 } },
      { id: 'v2', label: 'Pack Rat', type: 'passive', cost: 2,
        description: '+1 inventory size',
        effects: { inventorySize: 1 } },
      { id: 'v3', label: 'Thick Skin', type: 'passive', cost: 3,
        description: '+5% damage resistance',
        effects: { damageResistance: 0.05 } },
      { id: 'v4', label: 'First Aid', type: 'active', cost: 4,
        description: 'Heal 25% health',
        effects: { ability: 'first_aid', healPercent: 0.25, cooldown: 30 } },
      { id: 'v5', label: 'Extra Pockets', type: 'passive', cost: 5,
        description: '+2 inventory size',
        effects: { inventorySize: 2 } },
      { id: 'v6', label: 'Fortitude', type: 'passive', cost: 6,
        description: '+10% health regen rate',
        effects: { healthRegenMult: 1.10 } },
      { id: 'v7', label: 'Iron Skin', type: 'passive', cost: 7,
        description: '+10% damage resistance',
        effects: { damageResistance: 0.10 } },
      { id: 'v8', label: 'Medkit', type: 'active', cost: 8,
        description: 'Full heal + 10s regen boost',
        effects: { ability: 'medkit', cooldown: 60 } },
      { id: 'v9', label: 'Resilience', type: 'passive', cost: 9,
        description: '+15% damage resistance',
        effects: { damageResistance: 0.15 } },
      { id: 'v10', label: 'Last Stand', type: 'active', cost: 10,
        description: '10s invulnerability on low health',
        effects: { ability: 'last_stand', duration: 10, cooldown: 120 } },
    ],
  },
};

export const XP_SOURCES = {
  kill: { base: 100, headshot: 50, melee: 25 },
  mission: { objective: 200, completion: 500 },
  discovery: { area: 50, secret: 150 },
};

export const LEVEL_CAP = 50;

export function xpForLevel(level) {
  if (level >= LEVEL_CAP) return Infinity;
  return Math.floor(100 * Math.pow(level, 1.8));
}

export function skillPointsForLevel(level) {
  return Math.floor(level / 2) + 1;
}
